// These tests were completely generated by AI
using Xunit;
using Moq;
using EventProvider.Controllers;
using EventProvider.Business.Interfaces;
using EventProvider.Business.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace EventProvider.Tests
{
    public class EventControllerTests
    {
        [Fact]
        public async Task GetEventById_ReturnsOk_WhenEventExists()
        {
            var mockService = new Mock<IEventService>();
            var eventModel = new Event { Id = 1, Name = "Test" };
            mockService.Setup(s => s.GetEventByIdAsync(1)).ReturnsAsync(eventModel);
            var mockLogger = new Mock<ILogger<EventController>>();
            var controller = new EventController(mockService.Object, mockLogger.Object);

            var result = await controller.GetEventById(1);

            var okResult = Assert.IsType<OkObjectResult>(result);
            Assert.Equal(eventModel, okResult.Value);
        }


        [Fact]
        public async Task Create_ReturnsCreated_WhenServiceReturnsTrue()
        {
            var mockService = new Mock<IEventService>();
            var form = new EventRegistrationModel { Name = "Test" };
            mockService.Setup(s => s.CreateEventAsync(form)).ReturnsAsync(true);
            var mockLogger = new Mock<ILogger<EventController>>();
            var controller = new EventController(mockService.Object, mockLogger.Object);

            var result = await controller.Create(form);

            Assert.IsType<CreatedResult>(result);
        }

        [Fact]
        public async Task Create_ReturnsProblem_WhenServiceReturnsFalse()
        {
            var mockService = new Mock<IEventService>();
            var form = new EventRegistrationModel { Name = "Test" };
            mockService.Setup(s => s.CreateEventAsync(form)).ReturnsAsync(false);
            var mockLogger = new Mock<ILogger<EventController>>();
            var controller = new EventController(mockService.Object, mockLogger.Object);

            var result = await controller.Create(form);

            Assert.IsType<ObjectResult>(result); // Problem returns ObjectResult
        }

        [Fact]
        public async Task Create_ReturnsProblem_WhenServiceThrowsException()
        {
            var mockService = new Mock<IEventService>();
            var form = new EventRegistrationModel { Name = "Test" };
            mockService.Setup(s => s.CreateEventAsync(form)).ThrowsAsync(new Exception("Service error"));
            var mockLogger = new Mock<ILogger<EventController>>();
            var controller = new EventController(mockService.Object, mockLogger.Object);

            var result = await controller.Create(form);

            Assert.IsType<ObjectResult>(result);
        }
    }
}
